version: "3"

services:
  servicecenter:
    image: 121.37.4.50:5000/servicecomb/service-center
    ports:
      - "30100:30100"
  mysql:
    image: 121.37.4.50:5000/servicecomb-samples/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
  customer-manage:
    image: 121.37.4.50:5000/servicecomb-samples/updated
    working_dir: /servicecomb-samples/houserush/customer-manage
    command: ["mysql:3306", "--", "mvn", "-s", "/root/settings.xml", "spring-boot:run"]
    environment:
      servicecomb_service_registry_address: http://servicecenter:30100
      spring_datasource_url: jdbc:mysql://mysql:3306/customer?characterEncoding=utf8&useSSL=false
    ports:
      - "7779:7779"
  edge-service:
    image: 121.37.4.50:5000/servicecomb-samples/updated
    working_dir: /servicecomb-samples/houserush/edge-service
    command: ["mysql:3306", "--", "mvn", "-s", "/root/settings.xml", "spring-boot:run"]
    ports:
      - "9090:9090"
    environment:
      servicecomb_service_registry_address: http://servicecenter:30100
      servicecomb_rest_address: 0.0.0.0:9090
#  gateway:
#    depends_on:
#      - servicecenter
#    build:
#      context: .
#      dockerfile: gateway.dockerfile
#    environment:
#      servicecomb_service_registry_address: http://servicecenter:30100
#    ports:
#      - "8889:8889"
  house-order:
    image: 121.37.4.50:5000/servicecomb-samples/updated
    working_dir: /servicecomb-samples/houserush/house-order
    command: ["mysql:3306", "--", "mvn", "-s", "/root/settings.xml", "spring-boot:run"]
    environment:
      servicecomb_service_registry_address: http://servicecenter:30100
      spring_datasource_url: jdbc:mysql://mysql:3306/house_order?characterEncoding=utf8&useSSL=false
      spring_redis_host: redis
    ports:
      - "6788:6788"
  login:
    image: 121.37.4.50:5000/servicecomb-samples/updated
    working_dir: /servicecomb-samples/houserush/login
    command: ["mysql:3306", "--", "mvn", "-s", "/root/settings.xml", "spring-boot:run"]
    environment:
      servicecomb_service_registry_address: http://servicecenter:30100
      spring_datasource_url: jdbc:mysql://mysql:3306/login?characterEncoding=utf8&useSSL=false
    ports:
      - "6777:6777"
  realestate:
    image: 121.37.4.50:5000/servicecomb-samples/updated
    working_dir: /servicecomb-samples/houserush/realestate
    command: ["mysql:3306", "--", "mvn", "-s", "/root/settings.xml", "spring-boot:run"]
    environment:
      servicecomb_service_registry_address: http://servicecenter:30100
      spring_datasource_url: jdbc:mysql://mysql:3306/realestate?characterEncoding=utf8&useSSL=false
    ports:
      - "7771:7771"
  user-center:
    image: 121.37.4.50:5000/servicecomb-samples/updated
    working_dir: /servicecomb-samples/houserush/user-center
    command: ["mysql:3306", "--", "mvn", "-s", "/root/settings.xml", "spring-boot:run"]
    environment:
      servicecomb_service_registry_address: http://servicecenter:30100
    ports:
      - "6877:6877"
  redis:
    image: 121.37.4.50:5000/redis:3.2.9
    ports:
      - "6379:6379"
  nginx:
    image: 121.37.4.50:5000/servicecomb-samples/nginx
    ports:
      - "8080:8080"




