## Spring Boot configurations
server:
  port: 9091
  # servlet.path: /

servicecomb:
  service:
    application: porter-application
    name: website
    version: 0.0.1
    registry:
      address: https://cse.cn-south-1.myhuaweicloud.com
      instance:
        watch: false

  rest:
    address: 0.0.0.0:9091 # should be same with server.port to use web container
    ## static web site will token root
    servlet:
      urlPattern: /api/*

  metrics:
    publisher.defaultLog:
      enabled: false


  credentials:
    akskEnabled: true
    accessKey: add your ak/sk from huaweicloud
    secretKey: add your ak/sk from huaweicloud
    akskCustomCipher: default
    project: cn-south-1