## Spring Boot configurations
server:
  port: 9091
  # servlet.path: /

servicecomb:
  service:
    application: porter-application
    name: website
    version: 0.0.1
    registry:
      # Default using local service center
      address: http://localhost:30100
      # address: https://cse.cn-south-1.myhuaweicloud.com
      instance:
        watch: false
  kie:
    serverUri: http://localhost:30110

  rest:
    address: 0.0.0.0:9091 # should be same with server.port to use web container
    ## static web site will token root
    servlet:
      urlPattern: /api/*

  metrics:
    publisher.defaultLog:
      enabled: false

# Using Huawei Cloud Service Engine Professional Edition, AK/SK is required
#  credentials:
#    akskEnabled: true
#    accessKey: add your ak/sk from huaweicloud
#    secretKey: add your ak/sk from huaweicloud
#    akskCustomCipher: default
#    project: cn-south-1